---
- name: Release code
  hosts: all
  gather_facts: no
  pre_tasks:
    - apt: name=git
      become: yes
    - shell: "git config --global user.email 'anonymous@example.com' && git config --global user.name 'Anonymous'"
    - file: path="/tmp/myapp/releases/initial" state=directory
    - file: dest=/tmp/myapp/current src=releases/initial state=link
    - git: repo=https://github.com/Aplyca/ansible-role-release.git dest="/tmp/myapp/releases/initial" version=be5bd9b4191fd18461a6e67958ba60352a6aa141
  roles:
    - { role: Aplyca.Release, tags: ["release"] }
  post_tasks:
    - name: "TEST: Check if App was installed"
      stat:
        path: "/tmp/myapp/current"
      register: app_root
      failed_when: not (app_root.stat.islnk is defined and app_root.stat.islnk)
    - name: "TEST: Check if App is a git repo"
      stat:
        path: "/tmp/myapp/current/.git"
      register: app_repo
      failed_when: not (app_repo.stat.isdir is defined and app_repo.stat.isdir)
