---
- name: "Release variables:"
  debug: var=release

- name: Create release scritps directory
  sudo: yes
  file:
   path: "{{ release['scripts_path'] }}"
   state: directory
   mode: 0755
   owner: "{{ ansible_user_id }}"

- name: Create exclude list file
  template:
    src: exclude_list.txt.j2
    dest: "{{ release['scripts_path'] }}/exclude_list.txt"
    mode: 0744

- name: Create release script
  template:
    src: release.sh.j2
    dest: "{{ release['scripts_path'] }}/release.sh"
    mode: 0744

- name: "Execute release version"
  shell: "{{ release['scripts_path'] }}/release.sh {{ release['version'] }}"
  args:
    chdir: "{{ release['target'] }}/{{ release['project'] }}"
  register: result

- debug: var=result
