- debug: var=release verbosity=1
  tags: vars

- name: Initializing variables
  set_fact:
    step: false
    message: ""
    alert: "good"

- name: Validate if a new version can be released
  block:
    - name: Failsafe for tasks to check app
      block:
        - name: Tasks for checking app
          import_tasks: check-app.yml
      rescue:
        - name: Setting failed step
          set_fact:
            step: check-app
            alert: warning
            message: "The app '{{ release.project }}' is not properly installed"
        - name: Failing step
          fail:
            msg: "The app '{{ release.project }}' is not properly installed"

    - name: Failsafe for tasks before the release
      block:
        - name: Tasks before release
          import_tasks: pre-release.yml
      rescue:
        - name: Setting failed step
          set_fact:
            step: pre-release
            alert: warning
            message: "A task before the release failed, so it was aborted."
        - name: Abort release
          import_tasks: abort.yml
        - name: Failing step
          fail:
            msg: "A task before the release failed"

    - name: Failsafe for tasks during the release
      block:
        - name: Tasks during release
          import_tasks: release.yml
      rescue:
        - name: Setting failed step
          set_fact:
            step: release
            alert: danger
            message: "Some task during the release failed"
        - name: Failing step
          fail:
            msg: "Some task during the release failed"

    - name: Failsafe for tasks after the release
      block:
        - name: Tasks after release
          import_tasks: post-release.yml
      rescue:
        - name: Setting failed step
          set_fact:
            step: post-release
            message: "New code was successful released but a task after the release failed"
            alert: "warning"
        - name: Failing step
          fail:
            msg: "A tasks after the release failed"

  rescue:
    - name: Debug error
      debug:
        msg:
          - "Step: {{ step }}"
          - "Message: {{ message }}"
          - "alert: {{ alert }}"
  always:
    - name: Send Notifications
      import_tasks: notifications.yml
