---
- name: Send notification to Slack
  slack:
    token: "{{ release.slack.token }}"
    msg: "{{ release.slack.message }}"
    attachments:
      - title: "{{ release.semver.type | title() }} version {{ release_tag.version }} released by {{ release.releaser }} on {{ release.project | upper() }} {{ release.environment | title() }}"
        text: "{{ release.slack.description }}"
        color: good
        title_link: "{{ release.slack.title_link }}"
        author_name: "{{ release.slack.author_name }}"
        author_link: "{{ release.slack.author_link }}"
        author_icon: "{{ release.slack.author_icon }}"
        fields:
          - title: "Version change:"
            value: "{{ release.semver.type | title() }} version, <{{ release.semver.diff_url }}/{{ current_tag.stdout }}...{{ release_tag.version }}|from {{ current_tag.stdout }} to {{ release_tag.version }}>"
            short: true
          - title: "Changelog:"
            value: "{{ changelog.stdout }}"
            short: false
        footer: "{{ release.slack.footer }}"
        footer_icon: "{{ release.slack.footer_icon }}"
    username: "{{ release.slack.username }}"
    channel: "{{ release.slack.channel }}"
    icon_emoji: "{{ release.slack.icon_emoji }}"
  when: release.slack.token is defined and changelog is defined and release.semver.publish

- name: Debug notification info
  debug:
    verbosity: 1
    msg: "{{ lookup('template', release.webhook.message_template) }}"
  tags: vars

- name: Send webhook notification
  local_action: uri
  args:
    url: "{{ release.webhook.url }}"
    method: "{{ release.webhook.method }}"
    body: "{{ lookup('template', release.webhook.message_template) }}"
    body_format: json
    user: "{{ release.webhook.user }}"
    password: "{{ release.webhook.password }}"
  async: 3600
  poll: 0
  when: release.webhook.url
  become: false
