- name: "Run during commands"
  shell: "{{ item }}"
  environment: "{{ release.env_vars | default({}) }}"
  args:
    chdir: "{{ release.target }}/{{ release.project | lower() }}/{{ release.release_dirname }}/{{ release_dir.stdout }}"
  with_items: "{{ release.during_commands }}"

- name: Publish new release
  shell: "{{ item }}"
  args:
    chdir: "{{ release.target }}/{{ release.project | lower() }}"
  with_items:
    - "ln -sf {{ release.release_dirname }}/{{ release_dir.stdout }} latest"
    - "mv -T latest {{ release.release_symlink }}"
